spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://%主机IP%:3306/zr?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    # druid配置
    druid:
      max-wait: 50
      max-active: 5000
      min-idle: 5
      initial-size: 10
server:
  port: 8080
  servlet:
    context-path: /boot

# 日志输出等级
logging:
  level:
    com.ciusyan.bootcst: info
